// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "hts2_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// cgm_c
MatrixXd cgm_c(SEXP As, SEXP bs);
RcppExport SEXP hts2_cgm_c(SEXP AsSEXP, SEXP bsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type As(AsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type bs(bsSEXP);
    __result = Rcpp::wrap(cgm_c(As, bs));
    return __result;
END_RCPP
}
